[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#2A363B"

# Background color used for the sidebar and most interactive widget
secondaryBackgroundColor = "#4586E"

# Color used for almost all text.
textColor = "#FEFFFF"

[client]
toolbarMode = "minimal"